import { EmotionItem, QuadrantType } from '../types';

export const EMOTIONS: Record<QuadrantType, EmotionItem[]> = {
  red: [
    { id: 'r1', name: 'Anxious', quadrant: 'red', energy: 'high', pleasantness: 'unpleasant', definition: 'Uneasy, worried, or nervous about an upcoming event or uncertain outcome.' },
    { id: 'r2', name: 'Stressed', quadrant: 'red', energy: 'high', pleasantness: 'unpleasant', definition: 'Experiencing mental, physical, or emotional strain resulting from demanding circumstances.' },
    { id: 'r3', name: 'Overwhelmed', quadrant: 'red', energy: 'high', pleasantness: 'unpleasant', definition: 'Feeling buried or unable to cope under an excessive burden of tasks, thoughts, or emotions.' },
    { id: 'r4', name: 'Frustrated', quadrant: 'red', energy: 'high', pleasantness: 'unpleasant', definition: 'Upset or annoyed as a result of being unable to change or achieve something.' },
    { id: 'r5', name: 'Angry', quadrant: 'red', energy: 'high', pleasantness: 'unpleasant', definition: 'A strong feeling of annoyance, displeasure, or hostility in response to a perceived grievance.' },
    { id: 'r6', name: 'Worried', quadrant: 'red', energy: 'high', pleasantness: 'unpleasant', definition: 'Troubled or anxious about actual or potential problems and worst-case scenarios.' },
    { id: 'r7', name: 'Panicked', quadrant: 'red', energy: 'high', pleasantness: 'unpleasant', definition: 'Sudden uncontrollable fear or anxiety, often causing rapid heart rate and erratic action.' },
    { id: 'r8', name: 'Jittery', quadrant: 'red', energy: 'high', pleasantness: 'unpleasant', definition: 'Physically nervous, on edge, and jumpy with high physiological arousal.' },
    { id: 'r9', name: 'Nervous', quadrant: 'red', energy: 'high', pleasantness: 'unpleasant', definition: 'Easily agitated, apprehensive, or alarmed by an anticipated challenge.' },
    { id: 'r10', name: 'Restless', quadrant: 'red', energy: 'high', pleasantness: 'unpleasant', definition: 'Unable to relax, rest, or remain still as a result of anxiety or excess energy.' },
    { id: 'r11', name: 'Pressured', quadrant: 'red', energy: 'high', pleasantness: 'unpleasant', definition: 'Feeling urgent demands or coercive expectations from others or oneself.' },
    { id: 'r12', name: 'Uneasy', quadrant: 'red', energy: 'high', pleasantness: 'unpleasant', definition: 'Feeling a vague sense of distress, disquiet, or internal discomfort.' },
    { id: 'r13', name: 'Enraged', quadrant: 'red', energy: 'high', pleasantness: 'unpleasant', definition: 'Intensely angry, furious, or filled with rage.' },
    { id: 'r14', name: 'Livid', quadrant: 'red', energy: 'high', pleasantness: 'unpleasant', definition: 'Furiously angry; outraged to an extreme degree.' },
    { id: 'r15', name: 'Furious', quadrant: 'red', energy: 'high', pleasantness: 'unpleasant', definition: 'Extremely angry; full of intense fury and reactive passion.' },
    { id: 'r16', name: 'Jealous', quadrant: 'red', energy: 'high', pleasantness: 'unpleasant', definition: 'Feeling threatened, resentful, or protective over someone else’s attention or status.' },
    { id: 'r17', name: 'Envious', quadrant: 'red', energy: 'high', pleasantness: 'unpleasant', definition: 'Painful or resentful awareness of an advantage, trait, or possession enjoyed by another.' },
    { id: 'r18', name: 'Contempt', quadrant: 'red', energy: 'high', pleasantness: 'unpleasant', definition: 'Feeling that someone or something is worthless, inferior, or beneath consideration.' },
    { id: 'r19', name: 'Terrified', quadrant: 'red', energy: 'high', pleasantness: 'unpleasant', definition: 'Consumed or paralyzed with extreme terror and acute fear.' },
    { id: 'r20', name: 'Irate', quadrant: 'red', energy: 'high', pleasantness: 'unpleasant', definition: 'Characterized by fierce, focused, and burning anger.' },
    { id: 'r21', name: 'Frightened', quadrant: 'red', energy: 'high', pleasantness: 'unpleasant', definition: 'Afraid, anxious, or shocked by sudden danger or threat.' },
    { id: 'r22', name: 'Scared', quadrant: 'red', energy: 'high', pleasantness: 'unpleasant', definition: 'Fearful or frightened by an immediate real or imagined threat.' },
    { id: 'r23', name: 'Repulsed', quadrant: 'red', energy: 'high', pleasantness: 'unpleasant', definition: 'Intense aversion, disgust, or distaste toward something offensive.' },
    { id: 'r24', name: 'Troubled', quadrant: 'red', energy: 'high', pleasantness: 'unpleasant', definition: 'Beset by problems, mental distress, or deep concern.' },
    { id: 'r25', name: 'Shocked', quadrant: 'red', energy: 'high', pleasantness: 'unpleasant', definition: 'Experiencing sudden, overwhelming surprise or disbelief.' },
    { id: 'r26', name: 'Apprehensive', quadrant: 'red', energy: 'high', pleasantness: 'unpleasant', definition: 'Anxious or fearful that something bad or unpleasant is about to happen.' },
    { id: 'r27', name: 'Embarrassed', quadrant: 'red', energy: 'high', pleasantness: 'unpleasant', definition: 'Feeling self-conscious, awkward, or flustered in front of others.' },
    { id: 'r28', name: 'Impassioned', quadrant: 'red', energy: 'high', pleasantness: 'unpleasant', definition: 'Filled with or showing intense, fiery emotion or zeal.' },
    { id: 'r29', name: 'Annoyed', quadrant: 'red', energy: 'high', pleasantness: 'unpleasant', definition: 'Slightly irritated, bothered, or displeased by minor friction.' },
    { id: 'r30', name: 'Irritated', quadrant: 'red', energy: 'high', pleasantness: 'unpleasant', definition: 'Showing or feeling impatience, chafing, or annoyance.' },
    { id: 'r31', name: 'FOMO', quadrant: 'red', energy: 'high', pleasantness: 'unpleasant', definition: 'Fear Of Missing Out: anxiety that rewarding events are happening without you.' },
    { id: 'r32', name: 'Concerned', quadrant: 'red', energy: 'high', pleasantness: 'unpleasant', definition: 'Worried, troubled, or anxious on behalf of someone or a situation.' },
    { id: 'r33', name: 'Peeved', quadrant: 'red', energy: 'high', pleasantness: 'unpleasant', definition: 'Annoyed or irritated, especially by a repetitive or petty grievance.' },
    { id: 'r34', name: 'Hyper', quadrant: 'red', energy: 'high', pleasantness: 'unpleasant', definition: 'Overly active, jittery, and stimulated beyond comfortable equilibrium.' },
    { id: 'r35', name: 'Confused', quadrant: 'red', energy: 'high', pleasantness: 'unpleasant', definition: 'Unable to think clearly; disoriented, bewildered, or perplexed.' },
    { id: 'r36', name: 'Tense', quadrant: 'red', energy: 'high', pleasantness: 'unpleasant', definition: 'Unable to relax; physical muscles tight and mental state coiled for stress.' },
  ],
  yellow: [
    { id: 'y1', name: 'Joyful', quadrant: 'yellow', energy: 'high', pleasantness: 'pleasant', definition: 'Feeling, expressing, or causing great pleasure, elation, and happiness.' },
    { id: 'y2', name: 'Excited', quadrant: 'yellow', energy: 'high', pleasantness: 'pleasant', definition: 'Very enthusiastic and eager with high, positive physical energy.' },
    { id: 'y3', name: 'Energized', quadrant: 'yellow', energy: 'high', pleasantness: 'pleasant', definition: 'Filled with vitality, vigor, and ready enthusiasm to take on life.' },
    { id: 'y4', name: 'Happy', quadrant: 'yellow', energy: 'high', pleasantness: 'pleasant', definition: 'Feeling or showing pleasure, contentment, and radiant satisfaction.' },
    { id: 'y5', name: 'Optimistic', quadrant: 'yellow', energy: 'high', pleasantness: 'pleasant', definition: 'Hopeful and confident about the future and positive outcomes.' },
    { id: 'y6', name: 'Motivated', quadrant: 'yellow', energy: 'high', pleasantness: 'pleasant', definition: 'Stimulated with enthusiasm and drive to take purposeful action.' },
    { id: 'y7', name: 'Inspired', quadrant: 'yellow', energy: 'high', pleasantness: 'pleasant', definition: 'Mentally stimulated to do or feel something creative, meaningful, or bold.' },
    { id: 'y8', name: 'Proud', quadrant: 'yellow', energy: 'high', pleasantness: 'pleasant', definition: 'Feeling deep pleasure and satisfaction from an achievement or quality.' },
    { id: 'y9', name: 'Confident', quadrant: 'yellow', energy: 'high', pleasantness: 'pleasant', definition: 'Feeling certainty about one’s abilities, judgment, and strengths.' },
    { id: 'y10', name: 'Playful', quadrant: 'yellow', energy: 'high', pleasantness: 'pleasant', definition: 'Fond of games, laughter, and lighthearted, spirited amusement.' },
    { id: 'y11', name: 'Curious', quadrant: 'yellow', energy: 'high', pleasantness: 'pleasant', definition: 'Eager to learn, explore, discover, or know more about something.' },
    { id: 'y12', name: 'Cheerful', quadrant: 'yellow', energy: 'high', pleasantness: 'pleasant', definition: 'Noticeably happy, positive, and bright in spirit and demeanor.' },
    { id: 'y13', name: 'Surprised', quadrant: 'yellow', energy: 'high', pleasantness: 'pleasant', definition: 'Astonishment or wonder caused by something unexpected and positive.' },
    { id: 'y14', name: 'Pleasant', quadrant: 'yellow', energy: 'high', pleasantness: 'pleasant', definition: 'Giving a sense of happy satisfaction, enjoyment, or friendly comfort.' },
    { id: 'y15', name: 'Pleased', quadrant: 'yellow', energy: 'high', pleasantness: 'pleasant', definition: 'Feeling or showing warm satisfaction, approval, and content.' },
    { id: 'y16', name: 'Awe', quadrant: 'yellow', energy: 'high', pleasantness: 'pleasant', definition: 'A feeling of reverential respect and wonder at something vast or sublime.' },
    { id: 'y17', name: 'Determined', quadrant: 'yellow', energy: 'high', pleasantness: 'pleasant', definition: 'Having made a firm decision and resolved to overcome obstacles.' },
    { id: 'y18', name: 'Eager', quadrant: 'yellow', energy: 'high', pleasantness: 'pleasant', definition: 'Wanting to do or experience something very much; keen and enthusiastic.' },
    { id: 'y19', name: 'Focused', quadrant: 'yellow', energy: 'high', pleasantness: 'pleasant', definition: 'Directing full concentration, attention, and mental clarity on a single goal.' },
    { id: 'y20', name: 'Exhilarated', quadrant: 'yellow', energy: 'high', pleasantness: 'pleasant', definition: 'Feeling thrilled, animated, and intensely alive.' },
    { id: 'y21', name: 'Successful', quadrant: 'yellow', energy: 'high', pleasantness: 'pleasant', definition: 'Accomplishing an aim, milestone, or purpose with pride and validation.' },
    { id: 'y22', name: 'Enthusiastic', quadrant: 'yellow', energy: 'high', pleasantness: 'pleasant', definition: 'Having or showing intense and eager enjoyment, interest, or approval.' },
    { id: 'y23', name: 'Upbeat', quadrant: 'yellow', energy: 'high', pleasantness: 'pleasant', definition: 'Cheerful, optimistic, and buoyant in attitude and perspective.' },
    { id: 'y24', name: 'Alive', quadrant: 'yellow', energy: 'high', pleasantness: 'pleasant', definition: 'Awake, vibrant, pulsating with energy, and deeply engaged with life.' },
    { id: 'y25', name: 'Delighted', quadrant: 'yellow', energy: 'high', pleasantness: 'pleasant', definition: 'Feeling or showing immense pleasure and sparkling joy.' },
    { id: 'y26', name: 'Thrilled', quadrant: 'yellow', energy: 'high', pleasantness: 'pleasant', definition: 'Extremely pleased, excited, and invigorated by a thrilling experience.' },
    { id: 'y27', name: 'Amazed', quadrant: 'yellow', energy: 'high', pleasantness: 'pleasant', definition: 'Greatly surprised, astounded, or filled with positive wonder.' },
    { id: 'y28', name: 'Wishful', quadrant: 'yellow', energy: 'high', pleasantness: 'pleasant', definition: 'Having or showing a hopeful, positive longing or aspiration.' },
    { id: 'y29', name: 'Elated', quadrant: 'yellow', energy: 'high', pleasantness: 'pleasant', definition: 'Ecstatically happy, elevated, and riding high on good fortune.' },
    { id: 'y30', name: 'Productive', quadrant: 'yellow', energy: 'high', pleasantness: 'pleasant', definition: 'Achieving significant flow, useful output, and meaningful progress.' },
    { id: 'y31', name: 'Engaged', quadrant: 'yellow', energy: 'high', pleasantness: 'pleasant', definition: 'Deeply involved, absorbed, and actively participating.' },
    { id: 'y32', name: 'Hopeful', quadrant: 'yellow', energy: 'high', pleasantness: 'pleasant', definition: 'Feeling or inspiring bright expectation for the future.' },
    { id: 'y33', name: 'Ecstatic', quadrant: 'yellow', energy: 'high', pleasantness: 'pleasant', definition: 'Feeling or expressing overwhelming, euphoric joy and delight.' },
    { id: 'y34', name: 'Empowered', quadrant: 'yellow', energy: 'high', pleasantness: 'pleasant', definition: 'Confident, capable, and in control of one’s circumstances and destiny.' },
    { id: 'y35', name: 'Challenged', quadrant: 'yellow', energy: 'high', pleasantness: 'pleasant', definition: 'Invigorated and tested by a difficult but rewarding endeavor.' },
    { id: 'y36', name: 'Accomplished', quadrant: 'yellow', energy: 'high', pleasantness: 'pleasant', definition: 'Feeling fulfilled and satisfied after completing something demanding.' },
  ],
  blue: [
    { id: 'b1', name: 'Fatigued', quadrant: 'blue', energy: 'low', pleasantness: 'unpleasant', definition: 'Exhausted of physical or mental energy; feeling weary and depleted.' },
    { id: 'b2', name: 'Sad', quadrant: 'blue', energy: 'low', pleasantness: 'unpleasant', definition: 'Feeling sorrowful, downhearted, or burdened with grief.' },
    { id: 'b3', name: 'Tired', quadrant: 'blue', energy: 'low', pleasantness: 'unpleasant', definition: 'In need of rest, sleep, or physical recovery.' },
    { id: 'b4', name: 'Exhausted', quadrant: 'blue', energy: 'low', pleasantness: 'unpleasant', definition: 'Drained of all physical and mental strength; completely worn out.' },
    { id: 'b5', name: 'Burned out', quadrant: 'blue', energy: 'low', pleasantness: 'unpleasant', definition: 'Depleted, overwhelmed, and cynical from chronic, unmanaged stress.' },
    { id: 'b6', name: 'Down', quadrant: 'blue', energy: 'low', pleasantness: 'unpleasant', definition: 'Low in spirits; subdued, discouraged, or mildly depressed.' },
    { id: 'b7', name: 'Lonely', quadrant: 'blue', energy: 'low', pleasantness: 'unpleasant', definition: 'Feeling isolated or missing meaningful emotional connection with others.' },
    { id: 'b8', name: 'Numb', quadrant: 'blue', energy: 'low', pleasantness: 'unpleasant', definition: 'Lacking emotional feeling or physical sensation; emotionally detached.' },
    { id: 'b9', name: 'Hopeless', quadrant: 'blue', energy: 'low', pleasantness: 'unpleasant', definition: 'Feeling that a situation is impossible to resolve; lacking optimism.' },
    { id: 'b10', name: 'Disheartened', quadrant: 'blue', energy: 'low', pleasantness: 'unpleasant', definition: 'Having lost determination, confidence, or enthusiasm after a setback.' },
    { id: 'b11', name: 'Disappointed', quadrant: 'blue', energy: 'low', pleasantness: 'unpleasant', definition: 'Sad or displeased because expectations, hopes, or promises were unmet.' },
    { id: 'b12', name: 'Spent', quadrant: 'blue', energy: 'low', pleasantness: 'unpleasant', definition: 'Having used up all inner reserves of energy, patience, and stamina.' },
    { id: 'b13', name: 'Disgusted', quadrant: 'blue', energy: 'low', pleasantness: 'unpleasant', definition: 'Feeling intense repulsion, distaste, or aversion toward an event.' },
    { id: 'b14', name: 'Humiliated', quadrant: 'blue', energy: 'low', pleasantness: 'unpleasant', definition: 'Feeling deeply mortified, demeaned, or stripped of dignity.' },
    { id: 'b15', name: 'Pessimistic', quadrant: 'blue', energy: 'low', pleasantness: 'unpleasant', definition: 'Tending to see worst-case outcomes or believing effort will fail.' },
    { id: 'b16', name: 'Guilty', quadrant: 'blue', energy: 'low', pleasantness: 'unpleasant', definition: 'Feeling painful responsibility for a perceived wrongdoing or failure.' },
    { id: 'b17', name: 'Depressed', quadrant: 'blue', energy: 'low', pleasantness: 'unpleasant', definition: 'Persistent low mood, lack of vitality, and diminished pleasure in life.' },
    { id: 'b18', name: 'Miserable', quadrant: 'blue', energy: 'low', pleasantness: 'unpleasant', definition: 'Wretchedly unhappy, uncomfortable, or suffering in mind.' },
    { id: 'b19', name: 'Trapped', quadrant: 'blue', energy: 'low', pleasantness: 'unpleasant', definition: 'Feeling cornered or unable to escape an oppressive situation.' },
    { id: 'b20', name: 'Ashamed', quadrant: 'blue', energy: 'low', pleasantness: 'unpleasant', definition: 'Embarrassed or guilt-ridden because of one’s perceived flaws or mistakes.' },
    { id: 'b21', name: 'Vulnerable', quadrant: 'blue', energy: 'low', pleasantness: 'unpleasant', definition: 'Exposed to the possibility of being hurt, judged, or emotionally wounded.' },
    { id: 'b22', name: 'Despair', quadrant: 'blue', energy: 'low', pleasantness: 'unpleasant', definition: 'The profound, complete absence of hope.' },
    { id: 'b23', name: 'Insecure', quadrant: 'blue', energy: 'low', pleasantness: 'unpleasant', definition: 'Uncertain or anxious about oneself; lacking confidence in security.' },
    { id: 'b24', name: 'Lost', quadrant: 'blue', energy: 'low', pleasantness: 'unpleasant', definition: 'Unable to find one’s direction, bearings, or sense of purpose.' },
    { id: 'b25', name: 'Disconnected', quadrant: 'blue', energy: 'low', pleasantness: 'unpleasant', definition: 'Feeling severed from others, one’s surroundings, or one’s own body.' },
    { id: 'b26', name: 'Excluded', quadrant: 'blue', energy: 'low', pleasantness: 'unpleasant', definition: 'Left out of a group, conversation, or shared belonging.' },
    { id: 'b27', name: 'Alienated', quadrant: 'blue', energy: 'low', pleasantness: 'unpleasant', definition: 'Experiencing feelings of estrangement or isolation from the world.' },
    { id: 'b28', name: 'Glum', quadrant: 'blue', energy: 'low', pleasantness: 'unpleasant', definition: 'Looking or feeling dejected, quiet, and morose.' },
    { id: 'b29', name: 'Forlorn', quadrant: 'blue', energy: 'low', pleasantness: 'unpleasant', definition: 'Pitifully sad, abandoned, or desolate.' },
    { id: 'b30', name: 'Nostalgic', quadrant: 'blue', energy: 'low', pleasantness: 'unpleasant', definition: 'A sentimental longing for the past, tinged with wistful sorrow.' },
    { id: 'b31', name: 'Meh', quadrant: 'blue', energy: 'low', pleasantness: 'unpleasant', definition: 'Apathetic, uninspired, indifferent, and lacking emotional momentum.' },
    { id: 'b32', name: 'Discouraged', quadrant: 'blue', energy: 'low', pleasantness: 'unpleasant', definition: 'Having lost confidence or enthusiasm to continue trying.' },
    { id: 'b33', name: 'Bored', quadrant: 'blue', energy: 'low', pleasantness: 'unpleasant', definition: 'Feeling restless and weary through lack of interest or stimulation.' },
    { id: 'b34', name: 'Disengaged', quadrant: 'blue', energy: 'low', pleasantness: 'unpleasant', definition: 'Emotionally detached, withdrawn, and mentally checked out.' },
    { id: 'b35', name: 'Apathetic', quadrant: 'blue', energy: 'low', pleasantness: 'unpleasant', definition: 'Showing or feeling complete indifference or lack of concern.' },
    { id: 'b36', name: 'Helpless', quadrant: 'blue', energy: 'low', pleasantness: 'unpleasant', definition: 'Unable to defend oneself, change conditions, or act effectively.' },
  ],
  green: [
    { id: 'g1', name: 'Calm', quadrant: 'green', energy: 'low', pleasantness: 'pleasant', definition: 'Not showing or feeling nervousness, agitation, or anger; at peace.' },
    { id: 'g2', name: 'Peaceful', quadrant: 'green', energy: 'low', pleasantness: 'pleasant', definition: 'Free from disturbance, noise, or inner conflict; serene and quiet.' },
    { id: 'g3', name: 'Relaxed', quadrant: 'green', energy: 'low', pleasantness: 'pleasant', definition: 'Free from tension and anxiety; rested in body, muscles, and mind.' },
    { id: 'g4', name: 'Content', quadrant: 'green', energy: 'low', pleasantness: 'pleasant', definition: 'In a state of peaceful happiness and satisfaction with how things are.' },
    { id: 'g5', name: 'Grateful', quadrant: 'green', energy: 'low', pleasantness: 'pleasant', definition: 'Feeling or showing warm appreciation for kindness and blessings.' },
    { id: 'g6', name: 'At ease', quadrant: 'green', energy: 'low', pleasantness: 'pleasant', definition: 'Comfortable, unstressed, and free from worry or constraint.' },
    { id: 'g7', name: 'Comfortable', quadrant: 'green', energy: 'low', pleasantness: 'pleasant', definition: 'Providing or experiencing physical and emotional safety and ease.' },
    { id: 'g8', name: 'Chill', quadrant: 'green', energy: 'low', pleasantness: 'pleasant', definition: 'Easygoing, unhurried, and pleasantly mellow.' },
    { id: 'g9', name: 'Serene', quadrant: 'green', energy: 'low', pleasantness: 'pleasant', definition: 'Calm, peaceful, and untroubled; crystal clear and undisturbed.' },
    { id: 'g10', name: 'Tranquil', quadrant: 'green', energy: 'low', pleasantness: 'pleasant', definition: 'Free from commotion or noise; deeply quiet, still, and centered.' },
    { id: 'g11', name: 'Balanced', quadrant: 'green', energy: 'low', pleasantness: 'pleasant', definition: 'Emotionally stable, grounded, and living in inner equilibrium.' },
    { id: 'g12', name: 'Thoughtful', quadrant: 'green', energy: 'low', pleasantness: 'pleasant', definition: 'Reflective, considerate, and engaged in gentle introspection.' },
    { id: 'g13', name: 'Good', quadrant: 'green', energy: 'low', pleasantness: 'pleasant', definition: 'Pleasant, harmonious, and experiencing healthy well-being.' },
    { id: 'g14', name: 'Sympathetic', quadrant: 'green', energy: 'low', pleasantness: 'pleasant', definition: 'Feeling compassionate understanding and tender care for others.' },
    { id: 'g15', name: 'Mellow', quadrant: 'green', energy: 'low', pleasantness: 'pleasant', definition: 'Pleasantly smooth, soft, and free from harshness or tension.' },
    { id: 'g16', name: 'Carefree', quadrant: 'green', energy: 'low', pleasantness: 'pleasant', definition: 'Free from anxiety or heavy responsibility; light-hearted in spirit.' },
    { id: 'g17', name: 'Understood', quadrant: 'green', energy: 'low', pleasantness: 'pleasant', definition: 'Feeling truly heard, recognized, and validated for who you are.' },
    { id: 'g18', name: 'Appreciated', quadrant: 'green', energy: 'low', pleasantness: 'pleasant', definition: 'Recognized and valued for one’s presence, care, or contributions.' },
    { id: 'g19', name: 'Compassionate', quadrant: 'green', energy: 'low', pleasantness: 'pleasant', definition: 'Feeling deep sympathy and a warm desire to help or comfort.' },
    { id: 'g20', name: 'Empathetic', quadrant: 'green', energy: 'low', pleasantness: 'pleasant', definition: 'Showing an ability to intuitively understand and share another’s state.' },
    { id: 'g21', name: 'Thankful', quadrant: 'green', energy: 'low', pleasantness: 'pleasant', definition: 'Pleased, relieved, and expressing genuine gratitude.' },
    { id: 'g22', name: 'Respected', quadrant: 'green', energy: 'low', pleasantness: 'pleasant', definition: 'Admired, valued, and treated with honor and consideration.' },
    { id: 'g23', name: 'Supported', quadrant: 'green', energy: 'low', pleasantness: 'pleasant', definition: 'Comforted, upheld, and helped by trusted people.' },
    { id: 'g24', name: 'Included', quadrant: 'green', energy: 'low', pleasantness: 'pleasant', definition: 'Welcomed as an authentic part of a circle, family, or shared space.' },
    { id: 'g25', name: 'Safe', quadrant: 'green', energy: 'low', pleasantness: 'pleasant', definition: 'Protected from harm or danger; secure and resting in safety.' },
    { id: 'g26', name: 'Relieved', quadrant: 'green', energy: 'low', pleasantness: 'pleasant', definition: 'No longer feeling distress or worry after a difficulty has passed.' },
    { id: 'g27', name: 'Fulfilled', quadrant: 'green', energy: 'low', pleasantness: 'pleasant', definition: 'Feeling satisfied and whole because one’s values are being lived.' },
    { id: 'g28', name: 'Loved', quadrant: 'green', energy: 'low', pleasantness: 'pleasant', definition: 'Feeling deeply cared for, cherished, and treasured by loved ones.' },
    { id: 'g29', name: 'Valued', quadrant: 'green', energy: 'low', pleasantness: 'pleasant', definition: 'Feeling that your presence and life genuinely matter.' },
    { id: 'g30', name: 'Accepted', quadrant: 'green', energy: 'low', pleasantness: 'pleasant', definition: 'Embraced as one is, without condition, pretension, or judgment.' },
    { id: 'g31', name: 'Secure', quadrant: 'green', energy: 'low', pleasantness: 'pleasant', definition: 'Confident in one’s stability, safety, and emotional bedrock.' },
    { id: 'g32', name: 'Satisfied', quadrant: 'green', energy: 'low', pleasantness: 'pleasant', definition: 'Pleased because needs, desires, or expectations have been met.' },
    { id: 'g33', name: 'Blissful', quadrant: 'green', energy: 'low', pleasantness: 'pleasant', definition: 'Extremely happy; full of quiet, sublime spiritual or mental joy.' },
    { id: 'g34', name: 'Connected', quadrant: 'green', energy: 'low', pleasantness: 'pleasant', definition: 'Joined in meaningful communion with another person, nature, or life.' },
    { id: 'g35', name: 'Moved', quadrant: 'green', energy: 'low', pleasantness: 'pleasant', definition: 'Deeply touched and stirred by beauty, kindness, or significance.' },
    { id: 'g36', name: 'Blessed', quadrant: 'green', energy: 'low', pleasantness: 'pleasant', definition: 'Endowed with good fortune, divine grace, or heartfelt favor.' },
  ],
};

